language: csharp
mono: none
solution: IpcServiceFramework.sln
dotnet: 2.1.502
dist: trusty
sudo: required
script:
 - cd ./src
 - dotnet restore
 - dotnet build --configuration Release
 - dotnet test JKang.IpcServiceFramework.Core.Tests
